{{- if and .Values.cluster.enabled (eq .Values.mishards.discoveryClassName "kubernetes") }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "milvus.fullname" . }}-pods-list
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["list", "get", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "milvus.fullname" . }}-pods-list
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: {{ template "milvus.fullname" . }}-pods-list
  apiGroup: rbac.authorization.k8s.io
{{- end -}}