{{- if .Values.cluster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus.nginx.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    component: "nginx"
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: "nginx"
  template:
    metadata:
      labels:
{{ include "milvus.matchLabels" . | indent 8 }}
        component: "nginx"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-config.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: "wait-for-milvus"
        image: {{ .Values.initContainerImage | quote }}
        command:
        - 'sh'
        - '-c'
        - >
          {{- if .Values.externalMysql.enabled }}
          until nc -z -w 2 {{ .Values.externalMysql.ip }} {{ .Values.externalMysql.port }} 
          {{- else }}
          until nc -z -w 2 {{ .Release.Name }}-mysql 3306
          {{- end }}
          {{- if not (eq 0 (int .Values.readonly.replicas)) }}
          && nc -z -w 2 {{ template "milvus.readonly.fullname" . }} {{ .Values.service.port }}
          {{- else }}
          && nc -z -w 2 {{ template "milvus.writable.fullname" . }} {{ .Values.service.port }}
          && echo ready to go; do
            sleep 2;
          done;
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
          - containerPort: 19530
          - containerPort: 19121
        livenessProbe:
          tcpSocket:
            port: 19530
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
          tcpSocket:
            port: 19530
{{ toYaml .Values.readinessProbe | indent 10 }}
        resources:
          {{- toYaml .Values.nginx.resources | nindent 10 }}
        volumeMounts:
          - name: nginx-configmap
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: nginx-configmap
        configMap:
          name: {{ template "milvus.nginx.fullname" . }}
{{- end }}
