cache:
  insertBufferSize: 1GB
  cacheSize: 4GB

gpu:
  enabled: false

image:
  resources:
    limits:
      memory: "6Gi"
      cpu: "2.0"
    requests:
      memory: "4Gi"
      cpu: "1.0"

mysql:
  enabled: true
  persistence:
    enabled: false
    storageClass: default
    accessMode: ReadWriteOnce
    size: 5Gi
