cache:
  insertBufferSize: 1GB
  cacheSize: 4GB

image:
  resources:
    limits:
      memory: "6Gi"
      cpu: "2.0"
    requests:
      memory: "4Gi"
      cpu: "1.0"

gpu:
  enabled: false

mysql:
  enabled: false
