cache:
  insertBufferSize: 1GB
  cacheSize: 4GB

image:
  resources:
    limits:
      memory: "6Gi"
      cpu: "2.0"
      aliyun.com/gpu-mem: 2 # GiB
    requests:
      memory: "4Gi"
      cpu: "1.0"

gpu:
  enabled: true
  cacheSize: 2GB
  searchDevices:
    - gpu0
  buildIndexDevices:
    - gpu0

mysql:
  enabled: false
