name: Helm

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'charts/**'
      - 'ct.yaml'
      - '.github/workflows/lint-test.yml'
      - '!**.md'
      - '!**.txt'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'charts/**'
      - 'ct.yaml'
      - '.github/workflows/lint-test.yml'
      - '!**.md'
      - '!**.txt'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout Milvus Helm
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint
          config: ct.yaml
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'
      - name: Modify Values Yaml file
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'
        shell: bash
        run: |
          sed -i '/^mysql:/{n;s/true/false/;}' charts/milvus/values.yaml
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'
        with:
          command: install
          config: ct.yaml
